name: analogues
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cartopy=0.21
  - esmpy=8.4
  - xclim=0.44
  - pandas=1.3
  - panel=0.14
  - param=1.13
  - bokeh=2.4
  - statsmodels
  - numpy=1.22
  - clisops=0.11
  - dask=2023.8
  - geopandas=0.13
  - intake=0.7
  - joblib=1.3
  - jupyter=1.0
  - matplotlib=3.4
  - PyYAML=6.0
  - Shapely=2.0
  - xarray=2023.1
  - xesmf=0.7
  - geoviews=1.9
  - hvplot=0.8
  - pyogrio=0.6